#!/bin/bash
set -e

SCRIPT_DIR="$(dirname "$(realpath --no-symlinks "$0")")"
cd "$SCRIPT_DIR"

# --opt=jit
echo -e "\x1b[96m[DEBUG]: Compiling\x1b[0m"
python2.7 rpython/bin/rpython -Ojit targetlizzzard.py

echo -e "\x1b[96m[DEBUG]: Cleaning up\x1b[0m"
find . -name "*.pyc" -delete || true
find . -name "*.pyo" -delete || true
find . -name "__pycache__" -delete || true

echo -e "\x1b[96m[DEBUG]: Done\x1b[0m"